# Generated by Django 5.2.6 on 2025-11-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('sending', 'Sending'), ('completed', 'Completed')], default='pending', help_text='Estado actual del pedido', max_length=20),
        ),
    ]
